apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "lb-api-cloud-provider-manager.fullname" . }}
  labels:
    {{- include "lb-api-cloud-provider-manager.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lb-api-cloud-provider-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ toYaml .Values.config | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      labels:
        {{- include "lb-api-cloud-provider-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lb-api-cloud-provider-manager.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - --cloud-provider=lb-api
            - --leader-elect=true
            - --use-service-account-credentials
            - --cloud-config=/etc/cloud-provider-manager/cloud.yaml
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/etc/cloud-provider-manager/"
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "lb-api-cloud-provider-manager.fullname" . }}
            optional: false
