apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lb-api-cloud-provider-manager.fullname" . }}
  labels:
    {{- include "lb-api-cloud-provider-manager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
        - configmaps
    verbs:
        - create
        - get
        - list
        - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
