apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lb-api-cloud-provider-manager.fullname" . }}
  labels:
    {{- include "lb-api-cloud-provider-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lb-api-cloud-provider-manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "lb-api-cloud-provider-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
