apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lb-api-cloud-provider-manager.fullname" . }}
  labels:
    {{- include "lb-api-cloud-provider-manager.labels" . | nindent 4 }}
type: Opaque
data:
  cloud.yaml: {{ toYaml .Values.config | b64enc }}
