openapi: "3.0.0"
info:
  version: 0.1.0
  title: Loadbalancer API
  description: API to configure a loadbalancer
  contact:
    name: Sven Haardiek
    email: sven@haardiek.de
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
paths:
  /healthz:
    get:
      description: Health check endpoint
      operationId: getHealth
      responses:
        '200':
          description: Everything OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /loadbalancer:
    get:
      description: Get all loadbalancer
      operationId: getLoadbalancer
      responses:
        '200':
          description: List of all loadbalancer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/loadbalancer'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:

    loadbalancer:
      type: object
      properties:
        name:
          type: string
        frontends:
          type: array
          items:
            $ref: '#/components/schemas/frontend'

    frontend:
      type: object
      required:
        - port
        - backend
      properties:
        port:
          type: number
        backend:
          $ref: '#/components/schemas/backend'

    backend:
      type: object
      properties:
        server:
          type: array
          items:
            type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
