// Package generate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package generate

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Config defines model for config.
type Config struct {
	Frontends []struct {
		Backend struct {
			Server *[]string `json:"server,omitempty"`
		} `json:"backend"`
		Port int `json:"port"`
	} `json:"frontends"`
}

// Error defines model for error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Loadbalancer defines model for loadbalancer.
type Loadbalancer struct {
	Config Config  `json:"config"`
	Name   *string `json:"name,omitempty"`
	Status *Status `json:"status,omitempty"`
}

// Status defines model for status.
type Status struct {
	Hostname *string `json:"hostname,omitempty"`
	Ip       *string `json:"ip,omitempty"`
}

// Name defines model for name.
type Name = string

// CreateLoadBalancerJSONBody defines parameters for CreateLoadBalancer.
type CreateLoadBalancerJSONBody = Loadbalancer

// CreateLoadBalancerJSONRequestBody defines body for CreateLoadBalancer for application/json ContentType.
type CreateLoadBalancerJSONRequestBody = CreateLoadBalancerJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	GetHealth(ctx echo.Context) error

	// (GET /loadbalancers)
	GetLoadbalancers(ctx echo.Context) error

	// (DELETE /loadbalancers/{name})
	DeleteLoadBalancer(ctx echo.Context, name Name) error

	// (GET /loadbalancers/{name})
	GetLoadbalancer(ctx echo.Context, name Name) error

	// (PUT /loadbalancers/{name})
	CreateLoadBalancer(ctx echo.Context, name Name) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetLoadbalancers converts echo context to params.
func (w *ServerInterfaceWrapper) GetLoadbalancers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetLoadbalancers(ctx)
	return err
}

// DeleteLoadBalancer converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteLoadBalancer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteLoadBalancer(ctx, name)
	return err
}

// GetLoadbalancer converts echo context to params.
func (w *ServerInterfaceWrapper) GetLoadbalancer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetLoadbalancer(ctx, name)
	return err
}

// CreateLoadBalancer converts echo context to params.
func (w *ServerInterfaceWrapper) CreateLoadBalancer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name Name

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateLoadBalancer(ctx, name)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/healthz", wrapper.GetHealth)
	router.GET(baseURL+"/loadbalancers", wrapper.GetLoadbalancers)
	router.DELETE(baseURL+"/loadbalancers/:name", wrapper.DeleteLoadBalancer)
	router.GET(baseURL+"/loadbalancers/:name", wrapper.GetLoadbalancer)
	router.PUT(baseURL+"/loadbalancers/:name", wrapper.CreateLoadBalancer)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RX32/bNhD+Vwiub1UkuXbcRU9r96MN5qUFtrcgA2jqZLGRSJY8efEC/e8DKdmyTMXd",
	"gGArsCdZ1Mfj3fd9d5IfKVe1VhIkWpo9Us0MqwHB+DvJanDXHCw3QqNQkmb0htVAVEGwBFIplq9ZxSQH",
	"QyMq3HPNsKRRv7m7RNTA50YYyGmGpoGIWl5CzVxweGC1rhz0ar3kkC6XF/lrPrtY8PzyYl0si4u0mC/n",
	"xVX67aJY04jWQq5AbrCk2SyiuNNur0Uj5Ia2bbuP7SvgShZi4yszSoNBAX69MEoiyNzfCITahpg14/cg",
	"8/CBBbMFM9o5FDGLX8XzeJHN5vPXNHJkIBhHy+/xy+w2vbi6e/mCBmkfFpgxbEfbYUGtPwFHh9DK4Ogs",
	"d0REa/Yg6qam2fLycr709HT3AzlCImzA+LCDELddxOhQ6N3EoUFax/sHFqe2gjHKhOxxlcOojEW6CDON",
	"aA3Wss0YSm8Ukp9UI/OQwpPc/DFDlKkER+adyHNvnRcGCprRb5KhV5LeY0mPaqNDs/xjPxtg+QdZ7fat",
	"EVjDIsPGfimTHnXKQ99/fZ6HYFN8DOeMmSiVxbC6/WrcL8Vc1VPGFnqyQZ4QcJKKfYoOImShenmQ8a4h",
	"aiYqF2gL8ruSMZMLuI+9/P0Q+nULkrzvn7ikxhPtzcdrgop0HDUGCDsdbJXgIC0MQ5H+cv0bjWhj3MEl",
	"orZZkvBSKQusBztCkv63TWqBiW8ogZ6G1dEB5M3HaxrRLRjbJZTGszh1aKVBMi1oRudxGqfdQCm9KkkJ",
	"rMLyT/d7AxjO6ff+OeEl8HsCMtdKSNfuTlrmMNc5zeg7wA7onWi1ctm6YK/S1F2Y1pXgHp98si7w49Hw",
	"DiUc5/DjFswOSyE35MPPHfEFayrcKwgSv3zIOdd3Q6YNT24kPGjgCDk5YNqIJsfC2ie5ewdIWFWd2iCg",
	"bjWKNs3g367z8DY5V/Aoo3BABzyshEX3tj6txn59aiSPrrfaTo0KcOLb4we/HvbnWJgO5bR5O0COP21u",
	"p8sYIInv8vZuWtGpnHKyOlHmPyU3etrXx9SR9Y7cdG+Is95+Xv6ehY5xI4SsuLJyUn1douhmQpTvDTBv",
	"agl/nDd2h3wuY39uwOJble/+NU3OVTr+h9AGzpn9n53Ttu1fAQAA//9bIiOiqw0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
